title: "Suraj's Blog"
description: Talk Swift Again
url: https://freesuraj.github.io
author: Suraj Pathak
twitter:
  username: iOSCook
social:
  name: Suraj Pathak
  links:
    - https://twitter.com/iosCook
    - https://github.com/freesuraj
    - https://www.linkedin.com/in/freesuraj
    - http://stackoverflow.com/users/1198935/suraj-pathak

permalink: /:year/:month/:day/:title/
paginate: 5
highlighter: rouge
excerpt_separator: <!--more-->

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'CNAME']