# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: freesuraj
google_analytics: UA-56107651-2

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Suraj Pathak

description: World through a Coder's eyes
author:
  name: Suraj Pathak
  email: freesuraj@gmail.com
  github: freesuraj
  twitter: freesuraj
  pinterest: freesuraj
  about: about.html
  linkedin: freesuraj
  bio: Be genuine, be epic!
  email_md5: 9548ed5632bc606e4638a2a5fffd836a

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
about_path: about.html

BASE_PATH:
